### ISSUE TITLE
Autocompletion via WBID not returning gene/cgc-name

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#113]
Enter WBGene00015146 into autocompletion.

Expected:
```
{"matches":[{"gene/id":"WBGene00015146", "gene/cgc-name": "abi-1"}]}
```

Actual:
```
{"matches":[{"gene/id":"WBGene00015146"}]}
```

**Comment by mgrbyte** [comment]
@sibyl229 Not sure this is a bug.
Just wondering why the need for matching names when entering a WBGene ID as the search term?
I can make it do so, but atm the search only returns the term matched (WBGene ID is always returned, since it's the "primary identifier" for the entity)
I have a branch that has the other names returned for all matching search terms,
but that needs to include an empty string/nonce value where the attribute doesn't exist for a given gene.
e.g: If there's no `:gene/cgc-name` in the db,  then the search will return `:gene/cgc-name "",...

**Comment by sibyl229** [comment]
@mgrbyte It's not a huge deal. The use case I have is to resolve a gene ID in a form to get a more readable label (say cgc name). It's useful when displaying a filled form that has failed the validation. 

It's also a little inconsistent when autocompleting on cgc-name, the response contains both the cgc-name and WBID, while autocompleting on WBID, only the WBID is returned.

Without the functionality, the form that fails a validation looks like (see the rendered "Merge into gene" field):

![screen shot 2018-10-02 at 9 53 51 am](https://user-images.githubusercontent.com/1753893/46354099-cec96a80-c62b-11e8-83f8-07379a9434c8.png)

The more desirable behaviour might be like how autocompleting on partial cgc-name is currently handled, where both cgc-name and WBID are are returned in the response:

![screen shot 2018-10-02 at 9 53 36 am](https://user-images.githubusercontent.com/1753893/46353848-26b3a180-c62b-11e8-809a-f0edecc3713d.png)

**Comment by mgrbyte** [comment]
Yep, makes sense now! I hadn't twigged you were also using this endpoint for auto-completing in the form dialogs.
I will submit a PR soon with the changes.

**Comment by sibyl229** [comment]
Great! Thank you!

**Comment by mgrbyte** [comment]
Having blank values fails spec validation.
