### ISSUE TITLE
Merge event missing merge_from gene ID

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#148]
Prior to the refactor, the event in recent activities would include gene/id of merged_from gene. It's no longer happening now. Not sure if this is by design.

**Comment by mgrbyte** [comment]
Good catch! :+1: 
Merge event should have the new value against `:gene/merges` 
(And similarly against `:gene/splits` for split events)
This is another case where the changes list isn't pulling in the refs properly (#137 is another case I found)

**Comment by mgrbyte** [comment]
@sibyl229 I think this should be fixed from db5790f onward, can you check when you get a chance pls?

**Comment by sibyl229** [comment]
@mgrbyte It's much better!

I might need to fix the UI a bit, because it's a little too subtile on the UI which gene is the merge_from gene and which one is the merge_into gene.

![screen shot 2019-01-10 at 1 34 07 pm](https://user-images.githubusercontent.com/1753893/50989316-01adb500-14dd-11e9-80db-02ecc8904533.png)
![screen shot 2019-01-10 at 1 34 23 pm](https://user-images.githubusercontent.com/1753893/50989317-01adb500-14dd-11e9-8ab3-4bd92bf59b74.png)

What do you think?

I also want to double check with you what would be a good way to tell from the data response which gene is the "merge from" and which one is the "merge into".

**Comment by mgrbyte** [comment]
@sibyl229 
:+1: for making it more obvious
I think making the identifiers link-able in the table(s) would be good.

**Comment by sibyl229** [comment]
Hi @mgrbyte 

- Is the `:gene/merges` (the top level attribute key) the merge **into** gene?  Not sure if it's intentional, but in the change history, both the mergeInto gene and the mergeFrom gene assert `gene/merge`,

- Is the concept of "merge from" and "merge into" still useful to user?

- What would be a good way to tell from **the API response** whether a gene is the mergeInto gene or mergeFrom gene? Do you think grepping for history entries with changes in both `:gene/merges` and `:gene/status` would be a good idea?

I'm attaching the gene API responses after a merge event. 

![screen shot 2019-01-18 at 1 06 56 pm](https://user-images.githubusercontent.com/1753893/51404778-6f339400-1b22-11e9-8db7-10f1370f4e27.png)

**Comment by mgrbyte** [comment]
Hi @sibyl229 
The top level `:gene/merges` should be an array of all genes involved in a merge. 
The gene is "merged-from" if it's dead.

I think the concept/labels "merged-from/merged-into" are still useful (if nothing else but to make it clearer to the viewer). (confirmed by @Paul-Davis)

What's confusing here, is at _event_ time, the "merged-from" gene is the one that gets killed; i.e: 
In the `changes` list, If `gene/merges` present and `gene/status` = dead,  
Otherwise, merged into.

However, when _viewing_ the data later, it appears "the other way around" (or certainly reads better in this way)
i.e In the example above, WBGene00000001 has been _merged-from_ WBGene00000002,
     conversly "WBGene000000002" has been _merged-into_ WBGene00000001.

Talk about confusing! :tongue: 

*Solution?*
In the examples you've presented above, the gene on the left could have the *top-level* attributes "merged-from": [gene-on-the-right], and conversely, the one on the right should have "merged-into": [gene-on-the-left].

Hypothetically, a given gene could have both "merged-from" and "merged-into",
so this allows for that case too (rather than using the datomic ident `:gene/merges`)

I propose we keep `:gene/merges` in the `changes` list, as it should (?) be evident that if you're looking at say "WBGene00000001" that anything mentioned in the changes list as `gene/merges` is _another_ gene.

Edit: I've just committed f2a24c4 which implements this - could you test and see what you think?

**Comment by sibyl229** [comment]
Thanks @mgrbyte ! I will test it and let you know
