### ISSUE TITLE
Handle id_token expiration

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#25]
@mgrbyte the id_token expires after a short period of time, and I couldn't figure out a way to refresh them. Since are using the Sign-in workflow, which is distinct from OAuth2, the refresh_token concept may not be applicable here. 

Based on the documentation for Sign-in, it appears that this workflow is only intended for the initial authentication, while the application server is responsible for maintaining a session for subsequent client-server communication: https://developers.google.com/identity/sign-in/web/backend-auth (refer to the bottom of the article).

Right now I will sign out and sign back in to force the id_token to update. We probably need to figure out a better solution sometime.

**Comment by sibyl229** [comment]
Actually maybe I can redirect the user to the sign in page when there is a 401 error. What do you think? I will check the exact duration of a id_token before making any change

**Comment by mgrbyte** [comment]
I think your initial assessment is correct; the current implementation isn't adequate (or correct)
.
Although redirecting would work (albeit annoying users who use the site for more than a very quick session) , for the web side of things, it isn't an option at all for scripts

Unfortunately google has a plethora of different ways to implement auth: ouath2, google-sign, OpenID - and there are many many guides and tutorials for each.
OpenID we know is now deprecated and google sign in is the "new way" (i.e recommended).

After some more research last night I stumbled upon [this SO][1] article, the answer recommend [this guide][2].  on the alternatives, which I'm in agreement with, and plan to implement.

For the client side, this will be a tiny change (pass one-time code instead of token to back end),
no need for token auth on each request.
The back-end will be a bigger change...

[1]: https://stackoverflow.com/questions/32902734/how-to-make-google-sign-in-token-valid-for-longer-than-1-hour
[2]:  https://developers.google.com/identity/sign-in/web/server-side-flow

**Comment by mgrbyte** [comment]
[This][1] is what's currently implemented

[1]: https://developers.google.com/identity/sign-in/web/backend-auth

**Comment by mgrbyte** [comment]
[Here][1] is an overview of all the different google auth mechanisms and use-cases.

[1]: https://developers.google.com/identity/choose-auth

**Comment by mgrbyte** [comment]
@sibyl229 Good to close this now after #28 ?
