### ISSUE TITLE
Gene Merge - redirect to live gene

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/names#271]
I think it'd be good if we can make merge  redirect to the "merged into" gene (live one) after processing, as that's the gene the user is more likely to want to do more with.

**Comment by sibyl229** [comment]
A bit of a low tech solution. Instead of automatically redirecting, I included a link in the Snackbar to allow easier access to the merged and split into entity.

Here is an example with Split. Same goes for Merge:
![Screen Shot 2019-11-08 at 1 30 24 PM](https://user-images.githubusercontent.com/1753893/68502009-810b3280-022d-11ea-96ba-554ea786ddd4.png)
