### ISSUE TITLE
Additional attribute request (Species/Split_into/Merged_into) CalTech

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/names#305]
Split from #304 

@azurebrd - It would also be useful (for Caltech) to have the Species, Split_into, and Merged_into, but it's fine if it's out of scope.

**Comment by Paul-Davis** [comment]
Species has been added to the nameserver wb-names-export.jar dumper

**Comment by azurebrd** [comment]
Cool, thanks Paul :)

**Comment by Paul-Davis** [comment]
I think this can be closed as @azurebrd can query the NS via the api for the additional atributes?

**Comment by Paul-Davis** [comment]
@azurebrd could you close it that's true :)

**Comment by azurebrd** [comment]
Thanks, @Paul-Davis :)  I'm getting the genes nightly with the wb-names-export.jar because it would take too long to query through the API.  Should wb-names-export.jar be dumping split_into and merged_into ?  If it is, I need to check why it's not, and if it's not, could it ?  If it can, that's great.  If it can't, that's also okay, we can just keep getting that from the geneace dump when that gets updated.  Thanks !

**Comment by Paul-Davis** [comment]
@azurebrd so for now the wb-names-export.jar will not be including these attributes so the merge data will need to come from geneace. The genes.ace.gz file has all the merge/split data but can be up to 7 days behind the NS.

**Comment by azurebrd** [comment]
@Paul-Davis Cool cool, I'm good with it as it is then, thanks :)
